replicaCount: 1

image:
  repository: kanupriya18/calculator-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

